### ISSUE TITLE
Support BigQuery backend

### ISSUE THREAD

**Issue by yu-iskw** [metriql/metriql-superset#1]
## Motivation
I am not sure if we can technically support BigQuery backend. But, if we seamlessly integrate the dbt world with superset. That would be awesome!

**Comment by buremba** [comment]
Hey @yu-iskw, the integrations with the BI tools are for Metriql itself and Metriql already supports BigQuery. You can model the with dbt using BigQuery adapter, connect it to Metriql and expose the data to Superset. We use Snowflake [in the demo](https://metriql.com/integrations/bi-tools/superset) but if you use BigQuery target (or [any adapter here](https://metriql.com/introduction/supported-adapters)), it should work just fine.
